name: Cypress Tests

on: push

jobs:
  chrome:
    runs-on: ubuntu-22.04
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v5
        with:
          command: npm run e2e:headless
          browser: chrome
          
  firefox:
    runs-on: ubuntu-22.04
    name: E2E on Firefox
    steps:
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v5
        with:
          command: npm run e2e:headless
          browser: firefox
          
  edge:
    runs-on: ubuntu-22.04
    name: E2E on Edge
    steps:
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v5
        with:
          command: npm run e2e:headless
          browser: edge
            
  safari:
    runs-on: ubuntu-22.04
    name: E2E on Safari
    steps:
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v5
        with:
          command: npm run e2e:headless
          browser: webkit
